name: Deploy to GitHub Pages

on:
  push:
    branches: [ "master" ] # или другая ветка, если нужно

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Скачиваем код
      - name: Checkout source
        uses: actions/checkout@v3

      # 2. Устанавливаем Node.js
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # 3. Устанавливаем зависимости
      - name: Install dependencies
        run: npm ci

      # 4. Сборка проекта
      - name: Build
        run: npm run build

      # 5. Деплой в GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./dist
